### ISSUE TITLE
Posibility to add image to whiteboard

### ISSUE THREAD

**Issue by jessica88888** [Vanthiyadevan/whiteboard-socketio#3]
Hi devansvd,

Thank you for this great whiteboard! May I know is there any possibility to add image from upload form to whiteboard together with resize, rotate & moving function?

Thanks once again.

Best regards,
Jessica

**Comment by devansvd** [comment]
@jessica88888 apologies for the delay. It's a nice idea. Might try it in the future.

**Comment by jessica88888** [comment]
Hi @devansvd ,
It's ok, thanks for your reply. I closed this because it's quite similar with the other opened issue. 
Thanks once again for this great whiteboard!

Best regards,
Jessica
