### ISSUE TITLE
Doesnot works on mobile browsers

### ISSUE THREAD

**Issue by usmanehsan0613** [Vanthiyadevan/whiteboard-socketio#4]
hi , this is great code  and work. 
However i would bring this in your notice that this doesnot works in any mobile browser.
Any solution to this ?
Please advise

**Comment by devansvd** [comment]
@usmanehsan0613 Since listening only to mouse events it will not work on mobile touch. Add listen for touch events if you want. This is mentioned in the readme, will try to add this in the future.
